### ISSUE TITLE
Maps have apparent gaps in them when processing with scm-extractor/bw-chk

### ISSUE THREAD

**Issue by msikma** [tec27/scm-extractor#13]
Hi all. First of all, let me say that this library and [bw-chk](https://github.com/ShieldBattery/bw-chk) are both really nice work. I've been looking into generating map previews en masse, which is surprisingly difficult to find prior work on.

This package and bw-chk do an amazing job at solving the problem, but some newer maps have apparent gaps in them, such as Polypoid:

![(4)Polypoid 1 65 scx_x32](https://user-images.githubusercontent.com/1507745/159956477-49a5daec-0268-435b-8cf5-0f3baef54777.jpg)

A somewhat older map like New Taebaek Mountains works fine:

![(2)NEWTAEBAEK scx_x32](https://user-images.githubusercontent.com/1507745/159956859-a768f13d-b448-49f1-adc0-bf44964e6e15.jpg)

I've seen these gaps in SCMDraft as well, so I guess it's maybe some sort of compression or maybe an obfuscation trick? I'm not super familiar with the mapping scene so I don't know exactly what the deal is. When I make an edit of Polypoid and save it, the map none the less looks fine in-game, so I'm guessing there's something there that's being ignored by the actual engine.

I was just wondering if more is known about this, and whether these maps can potentially be supported in the future? I'd be willing to help out on it if possible.

**Comment by msikma** [comment]
After talking it over with a friend, he mentioned that these are possibly Remastered-only assets. I didn't realize there were so many of these, but he worked on a 1.16 compatible version of Eclipse and noticed that copying over sections of the map leads to there being invalid tiles in exactly the spots that are blacked out.

If this is the case, and that's what's causing this, is there any possibility of utilizing Remastered assets (specifically the "old graphics" assets) with these libraries?

**Comment by neivv** [comment]
The remastered tiles are expected to work if you extract their graphics (with [CascView](http://www.zezula.net/en/casc/main.html) for example) from SC:R installation. Since you seem to have files from 1.16.1 you'd only need to get the newer `.cv5` `.vx4ex` `.vr4` and `.wpe` files in `Tileset/` folder of the CASC archive.

**Comment by msikma** [comment]
Thank you! It works perfectly. Really appreciate your help.

<img width="599" alt="Screen Shot 2022-03-31 at 20 02 46" src="https://user-images.githubusercontent.com/1507745/161120719-8df87986-94b3-49d5-9c90-fc643f970564.png">

I had a look at the bw-chk source and, as I understand it, here's the minimum files needed to generate images of just about every map, is this correct?

* all files listed in `units.js` and `sprites.js`
* for all tilesets `['badlands', 'platform', 'install', 'ashworld', 'jungle', 'desert', 'ice', 'twilight']`, all files of extension `['.cv5', '.vx4', '.vr4', '.wpe', '.vx4ex']`
* the `*-nc.*` files are not needed (what does it mean, "no creep"?)
* all paths/filenames should be lowercase (`ashworld` instead of `AshWorld`) for case sensitive filesystems

I think this is correct and it seems to work but just thought I'd confirm just in case.

**Comment by neivv** [comment]
Correct, though you don't need to have `.vx4` files when you have the remastered's `.vx4ex` ones instead.

I think `-nc` files were 'No color cycling' versions of the tilesets and were used by the map editor. Not exactly sure how they differed, but they aren't needed here.
